[workspace]

members = [
    "program", "script", "recursive"
, "p2agg", "sp1eip712", "sp1-eip712-type"]

resolver = "2"

[profile.release]
opt-level = 3

[profile.bench]
opt-level = 3

[profile.fast]
inherits = "release"
debug = true
debug-assertions = true
